### PR TITLE
Make code compatible with neo4j-php-commons v3.0

### PR DESCRIPTION
**Pull request by annuh**
Rename following classes:

- NodeInterface to Node
- RecordViewInterface to RecordView

### CODE REVIEW

**Comment by ikwattro** [comment]
Thanks, this was unfortunately a BC break we introduced in commons.

**Comment by ikwattro** [comment]
@annuh There are some tests failing with the classes used in the tests. Please have a look or otherwise I'll check that out tonight.

**Comment by annuh** [comment]
@ikwattro Sorry, changed a bit too much. The tests are fixed now :)

**Comment by ikwattro** [comment]
Cool thanks ! I'll tag a new release soon

**Comment by ikwattro** [comment]
ok 1.0.1 released

**Pull request merged**
