### PR TITLE
Add a typecast in the docs, as the code does not strctly enforce types

### PR DESCRIPTION
**Pull request by gggeek**
Otherwise, if dev passes in a string such as "383", he will get no results

### CODE REVIEW

**Comment by ikwattro** [comment]
Currently as the method can accept a Label, a property key and a value, this can be that this value can be a string if he stores ids as strings (uuid for eg)

**Comment by gggeek** [comment]
but ids as strings will not work with the dataset in the example...

**Comment by ikwattro** [comment]
True, imo : 

1. not typecasting shows to the user that actually he can do whatever he wants to find the inout node
2. if typeasting is desired, this should definitevely not go into a method call but rather in a method argument as of php7 or in the method code.

nb: I saw you are based in London, we are running a recommendations meetup on thursday, you are of course welcome http://www.meetup.com/graphdb-london/events/228401874/?gj=co2&rv=co2

**Comment by gggeek** [comment]
Ok, so what about adding a one-line comment about this in the sample code ?

**Comment by ikwattro** [comment]
Would prefer that yes

**Comment by gggeek** [comment]
ok, will amend.

ps: thanks for the tip on the meetup. I tried to join, but am on the witing list...

**Comment by ikwattro** [comment]
If you would like to attend just tell me, no need for the list, you'll be my special guest :)

**Pull request closed without merging**
